services:
  - type: web
    name: ai-travel-planner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
    plan: free